name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tourism-website:${{ github.sha }} .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tourism-website:${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tourism-website:${{ github.sha }}
            docker stop tourism-green || true
            docker rm tourism-green || true
            docker run -d --name tourism-green -p 8081:80 ${{ secrets.DOCKER_USERNAME }}/tourism-website:${{ github.sha }}

            # Health check (optional)
            sleep 10
            curl --fail http://localhost:8081 || exit 1

            # Switch live traffic to green (via nginx symlink or reverse proxy update)
            docker stop tourism-blue || true
            docker rm tourism-blue || true
            docker rename tourism-green tourism-blue
