name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: second_runner

    env:
      BLUE_CONTAINER: tourism-blue
      GREEN_CONTAINER: tourism-green
      IMAGE_NAME: tourism-static

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Determine active container
        id: check
        run: |
          if docker ps | grep -q $BLUE_CONTAINER; then
            echo "ACTIVE=blue" >> $GITHUB_ENV
            echo "INACTIVE=green" >> $GITHUB_ENV
          else
            echo "ACTIVE=green" >> $GITHUB_ENV
            echo "INACTIVE=blue" >> $GITHUB_ENV
          fi

      - name: Stop and remove inactive container
        run: |
          docker stop tourism-${INACTIVE} || true
          docker rm tourism-${INACTIVE} || true

      - name: Run inactive container on port 8089
        run: |
          docker run -d --name tourism-${INACTIVE} -p 8089:80 $IMAGE_NAME

      - name: Health check (optional)
        run: |
          sleep 5
          curl -f http://localhost:8089 || (echo "Health check failed" && exit 1)

      - name: Swap NGINX to point to new container
        run: |
          docker stop tourism-${ACTIVE} || true
          docker rename tourism-${INACTIVE} tourism-${ACTIVE}

